### ISSUE TITLE
role "root" does not exist error

### ISSUE THREAD

**Issue by luongdangdung** [flyandi/mazda-enhanced-compass-map#2]
I follow instructions at https://github.com/flyandi/mazda-enhanced-compass-map
but I got error when run testimage.py

**Steps to reproduce:**

```
root@ubuntu:~/mazda-enhanced-compass-map# cd tiles/tilegen/base/
root@ubuntu:~/mazda-enhanced-compass-map/tiles/tilegen/base# ./testimage.py 
Traceback (most recent call last):
  File "./testimage.py", line 44, in <module>
    mapnik.load_map(m,mapfile)
RuntimeError: :
FATAL:  role "root" does not exist (encountered during parsing of layer 'amenity-areas' in map '../../tilestyles/mazda/mazda.xml')
```

How can I do to fix this?

**Comment by brettalcox** [comment]
I think you need to add a role in Postgres

**Comment by luongdangdung** [comment]
if I run **./testimage.py** command with _postgres_ user, is it possible?

**Comment by luongdangdung** [comment]
when I change to _postgres_ user, the bug is gone!
This issue is resolved by change to postres user to run command.
